seed: 42
per_device_train_batch_size: null
gradient_accumulation_steps: null
max_steps: null
learning_rate: 5.0e-5
warmup_steps: 100
lr_scheduler_type: cosine
weight_decay: 0.01
fp16: true #consider false
max_grad_norm: 1.0
gradient_checkpointing: true
dataloader_num_workers: 2
max_seq_length: 256

logging_steps: 50
logging_strategy: steps
log_level: info
disable_tqdm: false

save_steps: 500
save_total_limit: 4
